apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: so-s-poc-nemne
build:
  artifacts:
  - image: dlatqdlatq/tf_service
    context: api
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - api/kubernetes-manifests/api.service.yaml
    - inferences-server/kubernetes-manifests/inference.deployment.yaml
    - inferences-server/kubernetes-manifests/inference.service.yaml
    - kubernetes-manifests/test.ingress.yaml
