apiVersion: batch/v1
kind: Job
metadata:
  name: model-build
spec:
  template:
    spec:
      containers:
      - name: builder
        image: dlatqdlatq/model-build
        command: ["/bin/sh"]
        args:
          - "-c"
          - "export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python && python3 /models/main.py && bentoml containerize TransformerService:latest -t poc:v1"
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-socket-volume
          - mountPath: /models
            name: models
      volumes:
      - name: docker-socket-volume
        hostPath:
          path: /var/run/docker.sock
      - name: models
        hostPath:
          path: /Users/imseongbin/Desktop/workspace/so1s/so1s-poc-nemne/api/docker-dockerfiles/bentoml
      restartPolicy: Never
