apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-deployment
spec:
  selector:
    matchLabels:
      app: myinference
  template:
    metadata:
      labels:
        app: myinference
    spec:
      containers:
      - name: bentoml-inference
        image: dlatqdlatq/tf_service:latest
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 5000
      #   volumeMounts:
      #     - mountPath: /var/run/docker.sock
      #       name: docker-socket-volume
      # volumes:
      #   - name: docker-socket-volume
      #     hostPath:
      #       path: /var/run/docker.sock